name: Pull Request Title Validator
on: pull_request

jobs:
  require-valid-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: pragmatic-tools/pr-title-validator@1.0.0
        with:
          pattern: '^22\d\d\d\d\d\d\d+.*'
